### ISSUE TITLE
Enable state tests for constantinople

### ISSUE THREAD

**Issue by cburgdorf** [ethereum/py-evm#1152]
### What is wrong?

We currently do not run state tests against Constantinople. 

### How can it be fixed

- Pin the `fixtures` submodule to a newer version that contains the Constantinople tests (lookup which version geth is pinned against)
- Configure tests to run
- Make tests green

**Comment by cburgdorf** [comment]
I think I pushed this one as far as I could (see https://github.com/ethereum/py-evm/pull/1181) Both, the Py-EVM and ethereum/tests need to do some work before we can finish that.

**Comment by veox** [comment]
FTR, I'm trying to tease apart the issues, by first updating the `fixtures`, in PR #1224.

I've determined the last successful merge commit in `ethereum/tests` that `py-evm` still passes (`test_state_fixtures` in particular, since that's what's failing in PR #1181). Used `git bisect run` for that, with a [script](https://gist.github.com/veox/e626ccfe5702630d64716f719ca4b1b2); but it basically amounts to:

``` sh
source .virtualenv/*/bin/activate
cd fixtures
git checkout develop
git bisect start develop 47b09f42c0681548a00da5ab1c98808b368af49a --
git bisect run sh -c "cd .. && pytest --cache-clear --quiet --exitfirst --show-capture=no -k 'test_state_fixtures'"
git bisect log
```

I also tried every merge commit from current `develop` to `db8ae9de`, and they all have at least one failure.

-----

I think it'd be best to update the fixtures first before enabling `ConstantinopleVM`. Will try to step through the state failures one-by-one, to see which end (`py-evm` or `ethereum/tests`) is the culprit.

**Comment by veox** [comment]
See https://github.com/ethereum/py-evm/pull/1224#issuecomment-419714693 for status of the approach after PR #1224 was merged.

There were seemingly changes in the test specification format, and it might not be prudent to try and "break through" those `ethereum/tests` commits without understanding the changes first; and whether they're still relevant, or can be "jumped over".

(FTR, I've layed off working on this.)

**Comment by carver** [comment]
Confirmed finished in #1579
