### ISSUE TITLE
Lightchain integration test seems to fail intermittently

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#1168]
https://circleci.com/gh/ethereum/py-evm/58119?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pipermerriam** [comment]
I believe I've encountered this locally as well.  I think we still have a race condition of some sort during node startup.

**Comment by veox** [comment]
For ref, a "successful" start-up (prior to system upgrade) looked like this (as presented by `journalctl --user -b -u trinity --output=cat`):

```
Starting trinity ethereum node...
    INFO  08-15 15:58:53        main  Cleaning up unclean shutdown...
    INFO  08-15 15:58:53        main  Searching for process id files in /home/veox/.local/share/trinity/ropsten...
    INFO  08-15 15:58:53        main  Found 1 process from a previous run. Closing...
    INFO  08-15 15:58:53         ipc  Process 669 has already terminated
    INFO  08-15 15:58:53        main  Manually removed /home/veox/.local/share/trinity/ropsten/database.pid after killing process id 669
    INFO  08-15 15:58:53        main  Removed a dangling IPC socket file for database connections at /home/veox/.local/share/trinity/ropsten/db.ipc
trinity.service: Found left-over process 614 (python) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
Started trinity ethereum node.
    INFO  08-15 15:58:54        main
      ______     _       _ __
     /_  __/____(_)___  (_) /___  __
      / / / ___/ / __ \/ / __/ / / /
     / / / /  / / / / / / /_/ /_/ /
    /_/ /_/  /_/_/ /_/_/\__/\__, /
                           /____/
    INFO  08-15 15:58:54        main  Trinity/eth-0.2.0a30/linux/cpython3.6.6
    INFO  08-15 15:58:54        main  Trinity DEBUG log file is created at /home/veox/.local/share/trinity/ropsten/logs/trinity.log
    INFO  08-15 15:58:55        main  Started DB server process (pid=632)
    INFO  08-15 15:58:56        main  Started networking process (pid=651)
    INFO  08-15 15:58:58      server  Running server...
    INFO  08-15 15:58:58         nat  Setting up NAT portmap...
    INFO  08-15 15:58:58         ipc  IPC started at: /home/veox/.local/share/trinity/ropsten/jsonrpc.ipc
    INFO  08-15 15:59:03         nat  No UPNP-enabled devices found
...
```

-----

I've already started the upgrade process, so can't show a "failed" run - the `python` executable in the `virtualenv` relies on shared libraries from the base system, which are already gone.

They look like the [failed CI run linked in original report](https://circleci.com/gh/ethereum/py-evm/58119?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link).

What can't be seen from the log is that there's a noticeable delay between the printing of `Started {DB server,networking} process` lines, and the `IPC started at:` line. I don't think it's longer than the 3 seconds seen in the log above, though.

**Comment by veox** [comment]
A "failed" start-up (INFO-level `stdout` captured by `journalctl`, as well as DEBUG-level log):

https://gist.github.com/veox/3c6cd302d8fa0dd37caf8ae1193fc04f

A "successful" start-up (same files - ellipsised, since output to this continues):

https://gist.github.com/veox/028b81306eeb728d6c375c19261635a0

**Comment by pipermerriam** [comment]
I'm postulating this has something to do with a delay between when the IPC socket file is *present* on the filesystem and when it can actually be connected to, or something similar.  

You can see here: https://github.com/ethereum/py-evm/blob/0b395da06a8b6b5e8ac175324357a1df2cc465c8/trinity/main.py#L197

We do verify that the file is present on the filesystem before launching the networking process.  I suspect we need to try one of the following.

1. Modify the check to actually try to establish a socket connection.
2. Move the check to within the networking process startup.

And for either, we should add handling for this error so that we can shutdown cleanly and output a more user friendly error message.

**Comment by veox** [comment]
Here's the time `trinity` takes in `wait_for_ipc()` on this particular VM of mine; 20 back-to-back runs, sorted:

```
0.9533159732818604
0.9537031650543213
1.0101258754730225
1.104684829711914
1.254220962524414
2.058319330215454
2.15872859954834
2.3591904640197754
2.563837766647339
2.6105008125305176
2.61083984375
2.760026216506958
3.8138811588287354
4.66905665397644
5.67433762550354
6.079158544540405
6.830869197845459
8.687721967697144
9.094447374343872
9.243062257766724
```

I've tried many more times, and it's never exceeded 10 seconds.

The time taken, it seems, depends on hardware. We'd be seeing much more of this issue otherwise.
