### ISSUE TITLE
Persisting an iterable of headers or beacon blocks fails

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/py-evm#1648]
* py-evm Version: current master

### What is wrong?

`HeaderDB.persist_header_chain` iterates twice over the headers which fails if they are given in the form of an iterator.

First loop: https://github.com/ethereum/py-evm/blob/master/eth/db/header.py#L219-L227
Second loop: https://github.com/ethereum/py-evm/blob/master/eth/db/header.py#L240-L251
It also extracts the first element: https://github.com/ethereum/py-evm/blob/master/eth/db/header.py#L214

The same is bug is present in `eth.beacon.db.chain._persist_block_chain` where I originally encountered it.

### How can it be fixed

I can see three simple fixes:
- Handle everything in a single loop
- Convert the iterable to a tuple in the beginning
- Change the type hint to only accept sequences

**Comment by cburgdorf** [comment]
Restricting that to `Sequence[BlockHeader]` to me feels like the best choice here.

**Comment by cburgdorf** [comment]
Well, if we *can* handle everything in a single loop without sacrificing readability than maybe **that** would be the best choice as it would also be a slight performance improvement but I haven't given that much thought. I'm not a fan of converting it to a tuple in the beginning because then we are effectively looping over the data three times (converting to tuple + two existing loops)

**Comment by pipermerriam** [comment]
My preference:

1) look into handling things in a single loop.  If can be cleanly done, do the change **and**  add a test that uses a generator and ensure that it works as expected
2) if single loop isn't viable for whatever reason, use `Sequence` approach.
