### ISSUE TITLE
Beacon chain evacuation plan

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#1659]
### What is wrong?

Per #1594 - `trinity` and `p2p` modules are moving to a new home - but the beacon chain is still here and being developed rapidly.

There are other tradeoffs if we use new branches + submodules.

### How can it be fixed

Follow `trinity` to the new repo like a stalker (!!!)
1. Collect the "eth2-only" thing into `eth/beacon/` or `eth/shard/`.
    - `eth/rlp/sedes.py`: e.g., `uint384 = BigEndianInt(384)`
    - `eth/_utils/bls.py`: will be moved to `ethereum/py-ecc` repo
    - `eth/_utils/blobs.py`: blobs and chunks, merkle root tool <- sharding
    - `eth/constants.py`: chunks <- sharding

    I probably missed something, but it's not much.
2. Add an `eth2` module in `trinity` repo, where `eth2` module has `eth2/beacon` - like what `eth/beacon` is now.
3. Hope `eth2` will be strong enough to go back to `py-evm` one day.

**Comment by hwwhww** [comment]
@pipermerriam @cburgdorf @carver What do you think of it?

**Comment by cburgdorf** [comment]
>but I think it might be worth exploring options that keep the beacon code in the `py-evm` repository, or to at least try them before this approach.

I agree that we should give it a try. I know it is annoying because now PRs need to be reviewed in tandem ("Please review PR X in Trinity but make sure to test it on top of PR Y in Py-EVM") but that's the main disadvantage of standalone repos vs mono repos. With just two repositories I think the overhead is still manageable.

If it turns out to be too annoying to work under that model I agree that we should do what @hwwhww proposes and introduce an `eth2` module in the trinity repo until things have stabilized. The main danger here that I see is that the `eth2` namespace could turn into a quickfix area of the code base. E.g. consider that we need to change an API that trinity uses from `eth` and this API is used in both the beacon node and the eth1 node. The proper fix obviously is to make the change in the `Py-EVM` repo, cut a release and then make the change in Trinity. But since that's a lot of hassle one might be tempted to just copy and paste the API to the `eth2` namespace and make the changes there.

**Comment by jannikluhn** [comment]
To be honest, I suspect that the Trinity/py-evm split will be quite annoying for all work related to the beacon chain in Trinity. But I'm fine with trying it out for a couple of weeks and reevaluating when we know how it turned out in practice.

**Comment by cburgdorf** [comment]
@jannikluhn I feel you. I'm a fan of the mono repository approach for that exact reason and I've [stated before](https://github.com/ethereum/py-evm/issues/1502#issuecomment-442849638) that I'd rather keep `trinity` and `eth` in the same repository but there are pro arguments for separate repositories as well and the majority seemed to be in favor of the separation.

**Comment by pipermerriam** [comment]
I'll re-iterate that I have no problem with you guys choosing to move all Eth2.0 code into the `trinity` codebase under an `eth2` module.  The more I've thought about it, the more I am convinced that is the right move.

**Comment by hwwhww** [comment]
It looks like a good time now (less on-going PRs), I'm going to do the "`eth2` module in Py-EVM repo" PR.

**Comment by hwwhww** [comment]
close via ethereum/trinity#133
