### ISSUE TITLE
Set sharding protocol constants and configuration

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#246]
### What is wrong?
Set sharding protocol constants and configuration

### How can it be fixed

1. Protocol constants are listed here: https://github.com/ethereum/sharding/blob/develop/docs/doc.md#constants
  Find an appropriate place to set these parameters.

2. Node configuration
    * Related issue: Related to https://github.com/ethereum/py-evm/issues/198
    * Sharding only configuration: (Ref: https://github.com/ethereum/sharding/blob/develop/docs/doc.md#client-logic)
        * `validator_address`: "0x..." OR null
        * `watching`: [list of shard IDs]
    * DB setting (TBD): one DB for each shard

We can start `1. Protocol constants` now and leave `2. Node configuration` after #198 is solved or after we start `ShardManager` implementation.

**Comment by pipermerriam** [comment]
> Find an appropriate place to set these parameters.

* `evm.constants` - module is getting a bit full but a fine default location to start with.
* `evm.vm.forks.sharding.constants` - where the rest of the sharding code lives.
* `evm.sharding.constants` - assumes creation of a new `evm.sharding` module which might be appropriate.

Also, if these values need to be configurable and not *true* constants, I would propose making them configurable using environment variables.

```python
LOOKAHEAD_PERIODS = int(os.environ.get('PYEVM_SHARING_LOOKAHEAD_PERIODS', 4))
```

This pattern is fine, however, it will execute once at module load and be done.  I'd suggest something more akin to this so that it can be changed at runtime.

```python
def get_sharding_config():
    return {
        'LOOKAHEAD_PERIODS': int(os.environ.get('PYEVM_SHARING_LOOKAHEAD_PERIODS', 4)),
        ...
    {
```

This way anything that needs these constants, or to modify them at runtime can do so.

**Comment by hwwhww** [comment]
**Part 1: Protocol constants(config)** is done via #248.
Move **Part 2: Protocol constants** to Stage 2.
