### ISSUE TITLE
`sys.setrecursionlimit` is hard coded but should use `constants.STACK_DEPTH_LIMIT`

### ISSUE THREAD

**Issue by ycdk** [ethereum/py-evm#267]
**Problem**: presently `STACK_DEPTH_LIMIT` is defined dynamically in `constants` module but hard coded in `__init__.py`: 
https://github.com/ethereum/py-evm/blob/c54c8c2bdc3feea45659e58b86bc7c58ab0ade38/evm/__init__.py#L30

**Solution**: i believe should simply `from .constant import STACK_DEPTH_LIMIT` and use in call to `sys.setrecursionlimit`

**Comment by pipermerriam** [comment]
Looks like you figured it out, but..

Needs to be more than just the `STACK_DEPTH_LIMIT` since it actually takes more than a single stack frame (python stack frame) per EVM stack level.  Now, it might be prudent to have the VM class itself initialize this value to the appropriate limit since the limit *could* change, but I think it's safe to cross that bridge later if needed.

**Comment by ycdk** [comment]
yes sorry, realised this was not quite correct.

two question remain for me:

1. do we still need to fix  hard coded unit tests here that have 1024/1025?
https://github.com/ethereum/py-evm/blob/master/tests/core/stack/test_stack.py#L46

2. what if we receive specially crafted jmp/call opcodes? do we have a worst-case/adversarial test for such?

**Comment by pipermerriam** [comment]
- That test could be updated at whatever point that hard coded limit is changed.
- The JSON fixture based tests have tests for this type of thing, but I don't believe we have anything written in local tests to directly test this.
