### ISSUE TITLE
Switch to `BinaryTrie` state

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#289]
### What is wrong?
Shard chains use `BinaryTrie` for better efficiency.
See https://github.com/ethereum/wiki/wiki/Wishlist#trie

### How can it be fixed
1. Set `BinaryTrie` as the default trie of `FlatTrieBackend`.
2. Apply `FlatTrieBackend` in most sharding tests.

Will switch transaction trie and receipt trie in other tickets.

**Comment by NIC619** [comment]
@jannikluhn @hwwhww @pipermerriam Since gas consumption of creating a new account depends on `account_exist`:
```python
class Call(BaseCall):
    def compute_msg_extra_gas(self, computation, gas, to, value):
        …
        create_gas_fee = constants.GAS_NEWACCOUNT if not account_exists else 0
        ...
```
Unless we implement `account_exist` in FlatTrieBackend(or replace it's logic with `account_is_empty`), it seems that `FlatTrieBackend` is not backward compatible.
And if `FlatTrieBackend` is not backward compatible, I would say we can remove(or disable) `touch_account` as well.

**Comment by hwwhww** [comment]
hmm, so part of this issue also depends on https://github.com/ethereum/py-evm/issues/281 ?

> `FlatTrieBackend` is not backward compatible

It's could be compatible theoretically if we implement these functions, but practically, we don't need them. How about just raising `NotImplementedError` exceptions for these function + not testing `FlatTrieBackend` with `class Call`, just testing with the new `CallSharding`? Would that work?

**Comment by NIC619** [comment]
Yeah I think replacing with `CallSharding` would work for both this issue and #281 .

**Comment by NIC619** [comment]
My bad. `touch_account` is actually used in `ShardingComputation.apply_message` so `ShardingComputation.apply_message` needs to be changed too.

**Comment by hwwhww** [comment]
@NIC619  @jannikluhn  Could we modify `FlatTrieBackend.touch_account(address)` from 
```python
def touch_account(self, address):
        if not self.account_exists(address):
            self.set_nonce(address, 0)
            self.set_balance(address, 0)
            self.set_code(address, b'')
```

to

```python
def touch_account(self, address):
        if not self.account_is_empty(address):
            self.set_nonce(address, 0)
            self.set_balance(address, 0)
            self.set_code(address, b'')
```
?

**Comment by jannikluhn** [comment]
Yes, did this in https://github.com/ethereum/py-evm/pull/291

**Comment by NIC619** [comment]
Basically with `FlatTrieBackend` we don't need to create a new empty account if `message.to` does not exist so the gas creation fee(`constants.GAS_NEWACCOUNT`) does not apply unless we still charge it anyway.

But this removed gas fee would also result in consensus failure unless `FlatTrieBackend` is not going to be used by existing VMs and if Sharding is going to adopt `FlatTrieBackend` then this has to be mandated instead of being an option.

**Comment by NIC619** [comment]
@hwwhww @jannikluhn yeah modifying `touch_account` that way would work but the only caveat is that setting nonce/balance/code of not exist account to `0` or  `b''` in Binary Trie basically does nothing(i.e, the Trie won't change at all). So perhaps we can add a check on the underlying Trie type and act accordingly?

**Comment by NIC619** [comment]
> The reason being is that different backends result in different state roots. So the original protocol will keep using NestedTrieBackend, the sharding one will only use FlatTrieBackend.

Ahh I see. I was under the wrong impression. If this is the case, then there won't be a consensus failure problem.

And if sharing will only use `FlatTrieBackend` then I suppose we can just have `touch_account` raise `NotImplementedError` if used and remove the code that use it:
```python
class ShardingComputation(BaseComputation):
    def apply_message(self):
        ...
        with self.vm_state.state_db() as state_db:
            state_db.touch_account(self.msg.storage_address)
        ...
```

**Comment by hwwhww** [comment]
close via #355
