### ISSUE TITLE
JSON-fixture tests builder tool

### ISSUE THREAD

**Issue by hwwhww** [ethereum/py-evm#332]
### What is wrong?
Since we made (and may make more) protocol changes for Ethereum 2.0, it's better to be well-tested with more various JSON-fixture tests.

### How can it be fixed
As @pipermerriam suggested, we can write a tool to record EVM execution and export it in the JSON-fixture tests format.

**Comment by jannikluhn** [comment]
What do you think of the following scheme:

```
test1 = StateTest(
    name="CallIncrementsNonce"

    env={  # should have a sensible default because most tests won't touch it
        # ...
    },
    pre_state={
        ACCOUNT_ADDRESS: ACCOUNT_CODE,
    },

    transaction=UnsignedUserAccountTransaction(
        **DEFAULT_TX_PARAMS
    ).as_signed_transaction(PRIVATE_KEY),

    output=None,
    state_updates=[
        (ACCOUNT_ADDRESS, "storage", 0, 1),
    ],
    logs=[],
    gas_payment=0,
)

test2 = StateTest(...)

test_group = TestGroup([test1, test2])
print(test_group.to_json())
```

Initially I thought we'd want a more complex solution, but now I don't think this would make test creation more clear or concise. So basically, most fields from the JSON file are specified directly. Only the transaction is given by a transaction object, and instead of the complete final state only state changes are given. Changes can be either given as a dictionary (similar to `pre_state`) or as a flat list to avoid unnecessary nesting especially for storage. Now that I think about it, `pre_state` could be such a list as well.

`TestGroup` groups the tests (obviously) and creates the JSON representation. For this, the `post_state` is constructed and the state root is calculated (by setting the state directly, not by executing the transaction). If multiple tests share the same name they are required to have the same pre_state as well. In this case a single "parametrized" test is created (see "indexes" in the state test files).

If many tests share the same `pre_state` (one of the cases I thought a more complex design might be useful), `functools.partial` could be used to avoid repetition. To test a sequence of transactions, multiple tests have to be generated (because state tests allow only for a single transaction), but for that a helper can be used (saves setting env and pre_state):

```
test3 = test2.extend(
    # same parameters as StateTest, excluding env and pre_state
)
```

VMTests have mostly the same fields, but "transaction" is replaced with "exec":

```
test1 = VMTest(
    name="PAYGAS",
    env={
        # ...
    },
    pre_state={
        # ...
    },
    exec={
        "code": [PUSH1, b"\x00", PAYGAS],
    },
    state_updates=[],
    logs=[],
    paygas_gasprice=0,
)
```

So the only thing that is simplified compared to the raw JSON is that the executed code is specified using the mnemonics instead of raw bytecode. Also, the code is automatically deployed (i.e. the code doesn't have to be repeated in pre_state).

I'm gonna start implementing it like this, but I'm very willing to start all over again in case someone has a better approach.

**Comment by pipermerriam** [comment]
@jannikluhn I think this is a solid start, though I think we would benefit from being able to use at least some of the same infrastructure for both these tests and the actual JSON fixture tests.  Lets see what this looks like once some code exists and we can iterate from there. 👍
