### ISSUE TITLE
Trinity handling of KeyboardInterrupt

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#385]
### What is wrong?

Currently, trinity is not correctly handling `KeyboardInterrupt` for asyncio loop based processes.  
### How can it be fixed

Fill this in if you know how to fix it.

We need to make use of the [`asyncio.loop.add_signal_handler`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.add_signal_handler) API to do proper keyboard interrupt signal handling.

**Comment by namratachaudhary** [comment]
asyncio is very low-level

For KeyboardInterrupt, there are varied behaviours. Check this issue : https://github.com/python/asyncio/issues/341

It depends on how you trigger `KeyboardInterrupt`. When there is a callback that doesn't return - you need to use the signal to break through that, eg a loop like

```python
while True: 
    pass
```
Adding `asyncio.loop.add_signal_handler` _might_ not work because it wouldn't stop such a loop. 

Otoh, if there's an event loop or a queue running, and you do not want the signal to interrupt that routine, you can use `asyncio.loop.add_signal_handler` .

Another way to do it (naively), would be : 

```python
loop = asyncio.get_event_loop()

tasks = asyncio.gather(
        asyncio.async(some_task(second=5)),
        asyncio.async(some_task(seconds=10))
    )

try:
    loop.run_until_complete(tasks)
except KeyboardInterrupt as e:
    print("Caught keyboard interrupt..")
    tasks.cancel()
    loop.run_forever()
    tasks.exception()
finally:
    loop.close()
```
