### ISSUE TITLE
Add type annotations to Trinity code

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#386]
### What is wrong?

Need to add type annotations before Trinity code gets any larger.

### How can it be fixed

Add them

**Comment by cburgdorf** [comment]
I should be able to take that one. Seems like a good opportunity to explore the Trinity code base ;)

**Comment by cburgdorf** [comment]
How far do you intend to go here. Do you want to have the function return types annotated as well or just variables, parameters?

**Comment by cburgdorf** [comment]
Ok, turns out I'm running into unexpected challenges here. Having no experience with the type annotation support in Python I assumed things to behave differently.

This works as expected

```Python
def yay(val: bool):
  print(val)

yay(5)
```

Gives me:

```shell
$ mypy test.py 
test.py:11: error: Argument 1 to "yay" has incompatible type "int"; expected "bool"
```

But for instance, this doesn't raise any type error even though I assume it should (calling with `bool` where `str` is expected)

```Python
class Foo:
  def __init__(self):
    self.bar(True)

  def bar(self, val: str):
    print(val)
```

Same here, this doesn't raise a type error even though I would expect it to raise one since I'm assigning `bool` where a `str` is expected.

```Python
class Foo:
  bar:str = None
  def __init__(self):
    self.bar = True

```

Sorry, I don't mean to turn this into a free Python lesson for me but I'm not sure if I could really tackle this  task if the tooling doesn't give me the feedback I need. Chances are I'm completely approaching it wrong.

So, if you have pointers for me that would be gladly appreciated ;)

**Comment by gsalgado** [comment]
That was quite surprising to me as well, but after investigating a bit it looks like mypy will not perform any checks on code inside methods/functions that don't have any type annotations. If you change your `__init__()` signature to `def __init__(self) -> None:`, mypy will check the statements in its body and complain as we'd expect

**Comment by cburgdorf** [comment]
Thanks for your answer!

That's in fact quite surprising and dangerous because it means you may *think* everything is type checked and sound when in fact the code may have bugs and type checking was skipped altogether.

Anyway, this lets me move forward and as as side effect also answers my other question

>Do you want to have the function return types annotated as well or just variables, parameters?

With this in mind, we do want to annotate method/function return values.

**Comment by cburgdorf** [comment]
I started a PR (wip, not intended to get merged yet) and pinged you both regarding a question about how to approach generics. https://github.com/ethereum/py-evm/pull/407/commits/2dde65aa45eb05208a9364ad98a3fc9186f2a0d0#r170435219
