### ISSUE TITLE
Paygas refund issue

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/py-evm#413]
### What is wrong?

If a transaction fails after PAYGAS has been called, the sender ends up with his initial balance plus some additional funds. The reason for this seems to be that at the point of failure, the state is reverted to the pre gas payment state (i.e. the original balance), and on top of that the unused gas is refunded.

Here's the test case that discovered the bug: https://github.com/jannikluhn/py-evm/blob/de5365458c1839a47a1301551e3b62e54c5214ef/tests/fillers/vm_fillers/paygas_fillers.py#L322-L349

In this case, the account at `address` ends up with a balance of `138958` instead of `38958`.

### How can it be fixed

After reverting the state subtract the transaction fee again

Ping @NIC619

**Comment by NIC619** [comment]
Thanks for finding out the bug! I was thinking the same scenario but didn't realize that fee deducted in `PAYGAS` way is actually part of the intermediate state of transaction execution hence it's subjected to state revert.

This is a bit tricky and I don't feel quite comfortable subtracting the fee again after state reversion(though I don't have other solutions too ATM).
If we do this, we need to check if error was thrown(`computation.is_error`) in `execute_transaction` and take care the transaction fee/refund accordingly.
```python
def execute_transaction(self, transaction):
    
    …

    transaction_fee, gas_refund_amount = computation.compute_transaction_fee_and_refund()
    if computation.is_error:
        with state_db_cm() as state_db:
            state_db.delta_balance(transaction.to, -1 * transaction_fee)
    else:
        if gas_refund_amount:
            self.logger.debug(
                'TRANSACTION REFUND: %s -> %s',
                gas_refund_amount,
                encode_hex(transaction.to),
            )

            with state_db_cm() as state_db:
                state_db.delta_balance(transaction.to, gas_refund_amount)
    # Miner Fees
    self.logger.debug(
        'TRANSACTION FEE: %s',
        transaction_fee,
    )

    …

```
One good news is that since `PAYGAS` is only valid if triggered in top level call context, we don't have to check the result of every child call to see if `PAYGAS` is triggered but reverted in the child call.

Ping @pipermerriam @vbuterin

**Comment by pipermerriam** [comment]
Initial idea that comes to mind is enacting some way to bypass the journaling, or bury the state change deeper in the journal.  It's not immediately clear to me what the implementation of this would look like and I imagine it could get pretty messy.

Other ideas are to move the PAYGAS state change to occur outside of whatever snapshot/revert block it's currently in, moving it to a location *after* the reversion happens when a computation errors out.

Do either of these seem viable to you?

**Comment by NIC619** [comment]
> Other ideas are to move the PAYGAS state change to occur outside of whatever snapshot/revert block it's currently in, moving it to a location after the reversion happens when a computation errors out.

I've thought about this before but it seems there could be a DoS attack vector. If `PAYGAS` state change happens after transaction execution(i.e., in the post computation part), chances are that who is responsible for paying the transaction fee might turn out to be unable to afford it(transferred his ether away in the process) and hence render the transaction ineffective.

How about we don't make the state change immediately but instead store the transaction fee information in computation/msg object(or along with PAYGAS gas price)? Like a debt that liquidates only at the end of the transaction?
During transaction execution, whenever there's a value transfer take place we first check if this is paid by the account who's responsible for the transaction fee and if this value transfer will make him become insolvent. If yes, throw `InsufficientFund` exception and charge him the transaction fee.

**Comment by pipermerriam** [comment]
That worries me.  It couples the state database with EVM business logic which feels wrong.

This leaves me with the original idea, which is to add a mechanism to bypass the journal.  After taking a look at the code, I think this is quite doable and you should be able to validate this approach pretty easily with a basic test.

The `JournalDB` will need to be updated to allow bypassing the journal.  I think the best way to do this would be to add a `bypass_journal` flag to all of the `get/set/delete` methods which defaults to `False`

When `bypass_journal` is `True` the journal should do the following.

- proceed with the operation on the `self.wrapped_db`
- *if* the journal has any checkpoints, the earliest checkpoint should be updated to contain the new value for the key in question.

This code can be tested with the following somewhat simple test cases.

```python
jdb = JournalDB(...)

# case 1
s = jdb.snapshot()
jdb.set(k, v, bypass=True)
jdb.revert(s)
assert jdb.get(k) == v

# case 2
s = jdb.snapshot()
jdb.set(k, v)
jdb.set(k, v2, bypass=True)
jdb.revert(s)
assert jdb.get(k) == v2

# case 3
s = jdb.snapshot()
jdb.set(k, v, bypass=True)
jdb.set(k, v2)
jdb.revert(s)
assert jdb.get(k) == v

# case 4
s = jdb.snapshot()
jdb.set(k, v, bypass=True)
s2 = jdb.snapshot()
jdb.set(k, v2)
jdb.revert(s)
assert jdb.get(k) == v
```

Let me know what you think about this approach.  It feels cleaner than intertwining the actual PAYGAS business logic into different layers of the stack.  There will also need to be a change to the `AccountStateDB` object itself to tell it to bypass the journal which should probably just be a flag passed to it during instantiation.

**Comment by jannikluhn** [comment]
I tried to implement this as @pipermerriam suggested. It turned out though that integrating this into the account state dbs is not as easy as I thought, as they don't write to `JournalDB` directly but via `ImmutableDB`, `TrackedDB`, and/or the trie classes. So the `bypass` parameter would have to be passed through a lot of unrelated classes which I don't like.

Alternatively, one could not have a `bypass` parameter in each function call, but have an instance variable `JournalDB.bypassing` which can be turned on and off. This I like even less, because it's hard to debug and error prone.

What is wrong with my original proposal of simply redoing the gas payment after reverting the state? Something like this:
```Python
if computation.is_error:
    with state_db_cm() as state_db:
        assert state_db.get_balance(message.to) >= transaction_fee  # checked in PAYGAS call
        state_db.delta_balance(message.to, -transaction_fee)
```
It's not the most beautiful, but clear and easy to understand in my opinion.

**Comment by pipermerriam** [comment]
Thanks for exploring the idea.  Nothing wrong with your approach.  Make it so! 👍

**Comment by jannikluhn** [comment]
This was too optimistic:

```Python
assert state_db.get_balance(message.to) >= transaction_fee  # checked in PAYGAS call
```

What happens if the contract paying for the gas receives a payment before PAYGAS is called? Then the PAYGAS call would succeed at first. But later, after the transaction reverts for some other reason, the balance is insufficient. @NIC619 what's supposed to happen in this case? Are all state changes prior to PAYGAS irreversible? Are outgoing calls prior to PAYGAS illegal? Should we postpone all of this until sharding phase 2?

**Comment by NIC619** [comment]
@jannikluhn That's a good counter example. This is indeed more complicated than I imagined...
ping @vbuterin 

IMO one rule that can not be broken even if paying with `PAYGAS` is that whoever(`transaction.to`) that should pay for the transaction fee should at least have enough ether in the first place. We currently do it by charging the transaction fee during pre-computation.
So IMO the case where `contract receive payment before PAYGAS so that it has enough to pay for gas` is what we should prevent. My first intuition is to store the contract's initial balance somewhere(`transaction_context`?) before computation and in `PAYGAS` we checked against the contract's current balance and initial balance.

**Comment by vbuterin** [comment]
The solution that I had in mind (and thought I wrote somewhere?) is:

* We store the initial balance of the contract as part of the computation state
* PAYGAS(n) requires both (i) the current balance is at least `tx.gas * n` and (ii) the initial balance is at least `tx.gas * n`
* If PAYGAS gets reverted, `tx.gas * n`  also gets subtracted from the balance.

**Comment by hwwhww** [comment]
deactivate
