### ISSUE TITLE
Check the Kademlia pong results for hash of the ping

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#433]
### What is wrong?

The Kademlia p2p pong is supposed to be the hash of the ping, according to page 4 of [this (PDF) paper](http://www.cs.bu.edu/~goldbe/projects/eclipseEth.pdf), which has a nice summary of the p2p protocol. The paper claims that without this check, "*pong* messages [could be] sent from spoofed IP addresses".

Here's where I expected a check:

https://github.com/ethereum/py-evm/blob/eb7138ae67caab09c16d886f59e54639ad97b522/p2p/kademlia.py#L425-L433

Is this implemented somewhere else, or some reason that we don't need the check?

### How can it be fixed

Check the pong result against the hash of the ping, failing the pong if it is mismatched.

**Comment by gsalgado** [comment]
The link to the PDF paper seems to have been lost, and the one I have here doesn't seem to be the same

**Comment by carver** [comment]
Sorry about that, fixed the link. This is the sentence I read:

![image](https://user-images.githubusercontent.com/205327/36940952-a2916ec8-1f04-11e8-93b9-da716284e3d1.png)

Plus the footnote:

![image](https://user-images.githubusercontent.com/205327/36940957-b6f5a01e-1f04-11e8-9579-5edd31d6874e.png)

**Comment by gsalgado** [comment]
I had to refresh my memory because it's been a while since this code was written, but it turns out we are already performing that check when we receive a pong. This is how it works:
1. When we [send a ping, we get the msg hash](https://github.com/ethereum/py-evm/blob/master/p2p/discovery.py#L190-L191) and [generate a pingid, combining the hash with the node's ID](https://github.com/ethereum/py-evm/blob/master/p2p/kademlia.py#L470)
2. That pingid is then used to track [pongs we are waiting for](https://github.com/ethereum/py-evm/blob/master/p2p/kademlia.py#L484)
3. [If we get a pong with a hash different than what we expect, we drop it](https://github.com/ethereum/py-evm/blob/master/p2p/kademlia.py#L342-L349)
