### ISSUE TITLE
Look into using black for automated code formatting

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#476]
### What is wrong?

Enforcing code style is tedious.

### How can it be fixed

Look into using https://github.com/ambv/black/

**Comment by cburgdorf** [comment]
I looked into this. I like the idea of enforcing a common style to completely eliminate any debate about formatting. That said `black` is still alpha software so at this point we need to expect that certain formatting rules will still change over time. May not be a huge problem after all, just something to keep in mind. Even though it is alpha state software they do run a safety check by default that ensures that the AST from before the reformatting matches the AST from after the formatting. So at least, it shouldn't break code.

However, the only really configurable rule in `black` is the max-line width (having no options is the main feature after all) which means it is extremely opinionated and may hurt some peoples feelings. I'm absolutely fine to go with `black` if everyone else is fine as well. Just to give you a feel for the changes, here is what running black would do to the code.

https://github.com/cburgdorf/py-evm/commit/d8484e48e15d86e3bf62d2fac4d8ce2af75f34e4

If we do decide that we want to introduce black then it may be a good idea to do a bit of coordination among the team. There probably exist some bigger PRs that would have to go through many merge conflicts if they are forced to rebase on top of the reformatted source code.

So, in case we decide for using `black` I'd recommend we create a PR that prepares the changes to CI and coordinate to make the actual formatting changes after some other changes landed (if needed).

I also looked into the spacing rules that [triggered](https://github.com/ethereum/py-evm/pull/459#discussion_r175168638) this discussion. It turns out that the official style guide [favors to use the spaces around the `=` symbol](https://www.python.org/dev/peps/pep-0008/#variable-annotations) in this case. While I haven't found a way to configure `flake8` to enforce this rule `pylint` can enforce to have the spaces around the `=` symbol (but not the opposite!). Also `black` enforces this so that the code in question would be formatted as.

```python

    def __init__(
        self,
        shard_id: int,
        expected_period_number: int,
        period_start_prevhash: bytes,
        parent_hash: bytes,
        number: int,
        transaction_root: bytes = EMPTY_SHA3,
        coinbase: bytes = ZERO_ADDRESS,
        state_root: bytes = EMPTY_SHA3,
        receipt_root: bytes = EMPTY_SHA3,
        sig: bytes = b'',
    ) -> None:
        super(CollationHeader, self).__init__(
            shard_id=shard_id,
            expected_period_number=expected_period_number,
            period_start_prevhash=period_start_prevhash,
            parent_hash=parent_hash,
            transaction_root=transaction_root,
            coinbase=coinbase,
            state_root=state_root,
            receipt_root=receipt_root,
            number=number,
        )
```

Notice that spaces are only used for the `=` sign in the method signature and not for the call site when keywords are passed with values.

**Comment by pipermerriam** [comment]
Good research.  👍 

- lets wait on using `black`
- 👍 on following the pep8 guide for spaces around `=`
- waiting a bit more on the `flake8/pylint` issue, but worth opening an issue to track it (do you mind doing this?)

**Comment by cburgdorf** [comment]
@pipermerriam Created https://github.com/ethereum/py-evm/issues/485

**Comment by carver** [comment]
> lets wait on using `black`

Probably just as well, since it's still in alpha.

---

Yikes! There were in-line comments in between split lines: black joined the lines, and moved the comment down below the joined line. That loss of context could cause significant loss of comment semantics if we don't notice it during the main conversion.

https://github.com/cburgdorf/py-evm/commit/d8484e48e15d86e3bf62d2fac4d8ce2af75f34e4#diff-05178e170e27782a10a1498ec2aefdefL94

**Comment by cburgdorf** [comment]
Yeah, that whole part is something where I think one needs to disable the
formatter entirely because the formatting *really *serves comprehension
there.
