### ISSUE TITLE
Use `__slots__`

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#520]
Currently we use this pattern to denote that `MyThing` will have a `prop_a` property.

```python
class MyThing:
    prop_a = None
```

It looks like if we instead use `__slots__` we could see 40-50% reduction in memory footprint.

```python
class MyThing:
    __slots__ = ["prop_a"]
```

source: 

- https://docs.python.org/3/reference/datamodel.html#slots
- http://book.pythontips.com/en/latest/__slots__magic.html

**Comment by cburgdorf** [comment]
Interesting. So, it seems that if we would go down that path we'd lose out a lot of type safety features. By default `mypy` doesn't let us access attributes that aren't defined which is a good safety check to have. But it doesn't seem to recognize attributes defined via `slots` (leaving out for a moment that the string list donation doesn't let us specify the type of the property).

```python
class MyThing:
    __slots__ = ["prop_a"]

y = MyThing()
y.prop_a = 'test'
```

Leaves you with

```shell
$ mypy slots.py 
slots.py:5: error: "MyThing" has no attribute "prop_a"
```

Whereas the following works fine

```python
class MyThing:
    prop_a: str

y = MyThing()
y.prop_a = 'test'
```

**Plus**, it has the benefit of catching type bugs. E.g

```python
class MyThing:
    prop_a: str

y = MyThing()
y.prop_a = 4
```

```shell
$ mypy slots.py 
slots.py:14: error: Incompatible types in assignment (expression has type "int", variable has type "str")
```

>It looks like if we instead use __slots__ we could see 40-50% reduction in memory footprint.

I admit that I didn't really dive into *why* the `slots` construct would reduce the memory footprint that much but if it comes from the fact that we are pre-initializing all these attributes to `None` then I believe this won't be an issue with Python 3.6 anymore because there you don't need to assign `None` (or any other value) to an attribute just to denote it. You can simply declare it with its type and as far as I think this won't have any effect on runtime performance but be simply a hint for static analyzers such as `mypy`.

```python
class MyThing:
    prop_a: str
```

That's one downside of Python 3.5 that is also explicitly mentioned in [PEP526](https://www.python.org/dev/peps/pep-0526/).

>There's no way to annotate the type of an undefined variable; one needs to initialize it to None (e.g. a = None # type: int).

**Comment by pipermerriam** [comment]
Lame, and it doesn't appear there's a reasonable workaround right now.

**Comment by pipermerriam** [comment]
FYI @davesque

**Comment by carver** [comment]
mypy seems to work with this:

```py
class MyThing:
    __slots__ = ["prop_a"]
    prop_a: str

y = MyThing()
y.prop_a = 'test'
```

It's redundant, but at least you get the type checking and the performance boost.

**Comment by pipermerriam** [comment]
@carver doesn't actually work (unless my test was broken).  did you just run `mypy` or did you actually run the python code too.  Mine blew up when i tried to execute it.

**Comment by carver** [comment]
Works for me in py3.6.3:

```
$ python -i slots.py 
>>> y.prop_a
'test'
```

**Comment by cburgdorf** [comment]
>It's redundant, but at least you get the type checking and the performance boost.

@carver so this suggests that it isn't the pre-assignment (`prop_a = None`) that is eating unnecessary memory but rather that using `__slots__` gives you a performance boost in general. Do you mind sharing your memory footprint measurement code?

Also note that if it turns out that the memory boost is in fact related to the pre-assignment than this won't help for Python 3.5 because this just isn't valid Python 3.5 syntax.

```python
class MyThing:
    __slots__ = ["prop_a"]
    prop_a: str
```

It has to be this for Python 3.5

```
class MyThing:
    __slots__ = ["prop_a"]
    prop_a = None  # type: str
```

**Comment by carver** [comment]
> Do you mind sharing your memory footprint measurement code?

I was only trying to resolve the syntax failure, I haven't run any performance metrics on it.

Note that slots takes precedence over the py3.6 type annotations. Trying to add another variable after the slots has no effect:

```py
class MyThing:
    __slots__ = ["prop_a"]
    prop_a: str
    prop_b: str

y = MyThing()
y.prop_a = 'thang'
y.prop_b = 'that'
```

Produces:

```sh
$ python -i slots.py 
Traceback (most recent call last):
  File "slots.py", line 8, in <module>
    y.prop_b = 'that'
AttributeError: 'MyThing' object has no attribute 'prop_b'
```

> this won't help for Python 3.5

Right, but trinity only supports py3.6+, afaik.

**Comment by davesque** [comment]
@cburgdorf I haven't run any metrics on our projects, but there's some pretty good discussion [here](https://stackoverflow.com/a/28059785/751533) about the benefits of using `__slots__` as well as a table a ways down in that post that compares memory usage.

The basic use case seems to be when you've got lots of instances of some class which is used to store a small collection of values.

**Comment by davesque** [comment]
@cburgdorf 

> so this suggests that it isn't the pre-assignment (`prop_a = None`) that is eating unnecessary memory but rather that using `__slots__` gives you a performance boost in general.

Yes and no.  Using `__slots__` does give you speed and memory savings, however, there are a number of things that can cause a class to use a dict internally regardless of the presence of a `__slots__` directive in the class definition.  It may be that setting a class property with `prop_a = None` is one of those things.  Either way, class properties do not behave as usual with slotted classes.  From the [python docs](https://docs.python.org/3/reference/datamodel.html#notes-on-using-slots):

> __slots__ are implemented at the class level by creating descriptors (Implementing Descriptors) for each variable name. As a result, class attributes cannot be used to set default values for instance variables defined by __slots__; otherwise, the class attribute would overwrite the descriptor assignment.

Even though they don't behave as expected, if defining a class property with the same name as a slot doesn't cause Python to allocate a dict for a class, it could still be used as the anchor point for a type annotation comment.  Type annotations could also be provided on the arguments of an `__init__` method for a class if it has one which accepts all the values which are stored in a class.

Of course, none of this matters if usage of slots would only go into a version of py-evm that requires 3.6+ as @carver mentioned.

**Comment by cburgdorf** [comment]
>Right, but trinity only supports py3.6+, afaik.

Yep, `trinity` and `p2p` use 3.6 wheras the `evm` is still on 3.5.

@davesque thanks for the link and further explanation. 

>The basic use case seems to be when you've got lots of instances of some class which is used to store a small collection of values.

My general feeling and especially in respect to the loss of ergonomics (tracking of fields as strings) and caveats is that it would be worth to identify places where this could really have a big impact but not use it as a blanket approach to everything.

**Comment by davesque** [comment]
@cburgdorf Agreed.  Right tool for the right job.

**Comment by pipermerriam** [comment]
I think that the objects under the `Computation` class might be a good candidate for this.  For complex EVM execution we could end up with 1000+ instances of each of these objects in memory.
