### ISSUE TITLE
Use Circle-CI parallelism

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#605]
Circle CI will allow us to condense our tests down into a much smaller number of runs using parallelism.  We can setup a much smaller number of jobs, and instead setup the steps in a single job to be all of the different CI runs we need.  Circle lets us define that those steps can be run in parallel and will parallelize them.  With this approach we should be able to cut off a significant amount of overhead to our test runs.

**Comment by pipermerriam** [comment]
https://github.com/CircleCI-Public/circleci-demo-workflows/blob/fan-in-fan-out/.circleci/config.yml

**Comment by davesque** [comment]
I see now what you were talking about in our earlier conversation.

Not sure if we can really leverage this any more than we're doing already.  We already fire off different jobs for each python version.

One thing which could possibly be done is to break up different portions of the test suite into different jobs (like maybe separate jobs for unit and property tests?).

We could also create our own custom docker image for testing which could include some of the common dependencies such as tox pre-installed.  That could mean some extra maintenance when those dependencies need to be upgraded but it might still be worth doing.

**Comment by davesque** [comment]
Actually, sorry.  I guess it looks like we already split up different parts of the test suite into different tox envs and run a different job for each tox env and python version or something to that effect.  Also, I think we're saving and loading build caches properly so we might not really see any gains in that regard from a custom docker image.

Otherwise, everything you said sounds right.  Shouldn't do any unnecessary work (like cloning unneeded fixtures).  And were you implying that it might also be good to *reduce* the number of build jobs to avoid clogging up the pipeline for other projects by lumping tests across multiple parts of the test suite and multiple python version into single build jobs?  If you want to run multiple python versions in the same job, it probably *will* be necessary to make a custom docker image with multiple python versions unless a one already exists that we can use.

**Comment by pipermerriam** [comment]
No, I was actually thinking about reducing the number of builds that circle reports into the pull request as right now we get 31 different builds.  I was thinking we could reduce to 6 "builds" according to the list above.  I don't know how that would effect visibility into what failed though.

For now I think I'll accept status-quo and let us get migrated before we start trying further optimizations since there is lower hanging fruit.

**Comment by carver** [comment]
> For now I think I'll accept status-quo and let us get migrated before we start trying further optimizations since there is lower hanging fruit.

Up for closing this issue until it becomes a higher priority?
