### ISSUE TITLE
Figure out trinity p2p architecture

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/py-evm#668]
### What is wrong?

I started trying in https://github.com/ethereum/py-evm/pull/664 to do some refactoring in the p2p/trinity code around `LightChain` but I'm struggling to form a cohesive picture of the architecture.

1. We have a `Server` class which is slated to be used as the *common* entry point for running *chains*.
2. We have the `ChainSyncer` and  `RegularChainSyncer` classes which appear to serve *roughly* the same role as `LightChain` currently serves.
3. We have some other `Syncer` classes like `StateSyncer` which seem to serve slightly different roles.

### How can it be fixed

I'm hoping we can find a way to re-organize things to fit something like the following.

- A single class for each of *light*, *fast* and *regular* which know how to perform the syncing logic for each of those operating modes.
  - `LightSync`, `FastSync`, `FullSync` ?
- A single class for both *light* and *full* which exposes the full networking API (currently handled by `ChainSyncer` and `LightChain`).
  - Does **not** implement syncing logic.
  - Exposes APIs for sending and receiving data over the network
  - `LightClient`, `FullClient`
  - `LightSync` gets access to `LightClient` to perform networking tasks.
  - Both `FastSync` and `FullSync` get access to `FullClient` for network interactions.
  - `FullClient` probably handles switchover from `FastSync` to `FullSync`.
- One or more `Server` classes which are the standard entry point into running the trinity networking process.
  - Handles peer pool, discovery, ...
  - Handles running the `LightClient` and `FullClient` classes.

Then for some glue to hold it all together:

- A `ChainOverNetwork` class which implements the `BaseChain` API, however, it internally gets access to the

**Comment by gsalgado** [comment]
Yeah, things are still a bit messy in the `p2p` package, and I apologize for that. I have some plans (which I haven't gotten to working on yet because I got stuck trying to figure out some issues with how we're using `CancelToken`s), and I hope those will make things more obvious.

So, you're right that `Server` is supposed to be the main entry point. It will run `DiscoveryProtocol`, `PeerPool`, authenticate incoming peer connections (which should eventually be moved into its separate service), and run the service responsible for chain sync. 

Now, for the chain sync service, my plan is to have only `FullNodeSyncer` and `LightNodeSyncer`, where the latter will be factored out from the existing `LightChain` (or even from `FullNodeSyncer`). These are supposed to make sure we're always in sync, but won't provide APIs for chain/state data retrieval themselves -- that would stay in the current `Chain` service offered by `trinity` (with possibly a separate one that can fetch data on-demand, for when we're in light mode)

Finally, to clarify the state of the current `*Syncer` classes:
 - `ChainSyncer`: does the chain part of fast-sync, fetching/storing headers, bodies and receipts 
 - `StateDownloader`: does the state part of fast-sync, fetching/storing the whole state trie starting from a given root hash
 - `RegularChainSyncer`: does the regular sync, fetching headers/bodies and importing them
 
I'm thinking of renaming the first to `FastChainSyncer`, but those are all wrapped by `FullNodeSyncer` anyway.

**Comment by gsalgado** [comment]
Now answering some specifics:

> A single class for each of light, fast and regular which know how to perform the syncing logic for each of those operating modes. LightSync, FastSync, FullSync ?

There's actually only two modes -- light and full. When doing a full sync we might [start with a fast-sync if we are too far behind](https://github.com/ethereum/py-evm/issues/654) but once we've caught up we switch to regular-sync. That is handled by `FullNodeSyncer`

> A single class for both light and full which exposes the full networking API (currently handled by ChainSyncer and LightChain). 
>  - Does not implement syncing logic.
>  - Exposes APIs for sending and receiving data over the network
>  - LightClient, FullClient
>  - LightSync gets access to LightClient to perform networking tasks.
>  - Both FastSync and FullSync get access to FullClient for network interactions.

I think this is well encapsulated in peer (`ETHPeer` and `LESPeer`) and protocol classes. The sync services already delegate to those for network requests

**Comment by carver** [comment]
Replaced by #1060 I suppose
