### ISSUE TITLE
Shard syncer tests are nearly impossible to debug and take a long time to run

### ISSUE THREAD

**Issue by gsalgado** [ethereum/py-evm#688]
So, I didn't notice these new tests until they were merged, and I only did because my latest PR (#684) introduced some changes to `p2p.Server` that caused those tests to break. Unfortunately, they are quite complex, high-level, integration tests that give no visibility into what's going on under the hood, so when they break it is a nightmare to debug. Also, [they take a really long time to run](https://circleci.com/gh/ethereum/py-evm/8621?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):

> 19.36s call     tests/p2p/test_sharding.py::test_shard_syncer[3-connections1]
> 18.91s call     tests/p2p/test_sharding.py::test_shard_syncer[3-connections2]
> 10.41s call     tests/p2p/test_sharding.py::test_shard_syncer[2-connections0]

At this point, I understand writing unit tests for those parts will be tricky, but having a complex integration test like this as part of our CI is likely to slow down development of p2p-related code significantly -- I just spent more than 1h to get them to pass again. I think we'd be better off skipping those tests in CI, the same way we do for the tests in `tests/p2p/test_lightchain_integration.py`

**Comment by carver** [comment]
I thought sharding was dropped from the repo in https://github.com/ethereum/py-evm/pull/518 - if that's correct, then the tests seem like cruft. But I haven't been following the sharding work closely enough to be sure.

**Comment by jannikluhn** [comment]
Sorry for that! I'm also not happy with those tests, but just disabling them because they break is not a good long-term solution. The shard syncer and similar services (like the various chain syncers) are important components which should be tested in the CI (and are logic wise comparatively simple as well -- the shard syncer is at least).

I think the root issue is that there isn't an easy way to test the high-level service code only without running all of the low level code networking code as well. Do you think creating a `MockPeerPool` that mocks all the handshaking/connection/message passing stuff away, but has the right interface plus some entry points for test functions (like `add_peer`, `remove_peer`) would be a viable solution?

> I thought sharding was dropped from the repo in #518 - if that's correct, then the tests seem like cruft.

No, the code that belonged to a now deprecated specification, the tests here are new.

**Comment by gsalgado** [comment]
> Sorry for that! I'm also not happy with those tests, but just disabling them because they break is not a good long-term solution

It's not because they break that I suggest we skip them during the usual CI, it's because running a p2p.Server means running a PeerPool, DiscoveryProtocol, the coroutine that periodically refreshes the NAT portmap the asyncio server that listens for incoming peer connections, and now the syncer as well. We do need an integration test to make sure that all those things work together, but it should be a very basic _integration_ test. I think tests for the shard syncer (or any other parts of py-evm) that run as part of our CI should not be running all of these services, because it makes the tests very fragile and hard to debug. And the shard syncer tests make things even worse because they do nasty things (like setting chaindb to None in p2p.Server) that should not be expected to work.

I think it might be worth try mocking those services, yeah
