### ISSUE TITLE
After Byzantium, stop calculating state root after each transaction at all

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#705]
### What is wrong?

Persisting all account changes to the trie and calculating the new state root is expensive. After Byzantium, we no longer need to calculate the state root after each transaction (because it has been removed from the receipt).

### How can it be fixed

Stop returning state root after every `apply_transaction()`, instead generating it only if the receipt requires it.

(Depends on PR #704 )

**Comment by rayrapetyan** [comment]
@carver, state root is being updated in function "make_state_root" inside:
```
self._journaldb.persist()
self._journaltrie.persist()
```
calls. 
"stop calculating state root" also mean stop calling persist() (which I think is wrong?)
So do you mean "make_state_root" shouldn't be called from apply_transaction at all? 
Otherwise I don't see a way to separate state storing (persisting) and state root recalculation, this is an internal logic in DB and trie.hexary (inside persist() call).
Please clarify. Thanks.

**Comment by pipermerriam** [comment]
@rayrapetyan this is going to be an incomplete answer, but I hope it points you in the right direction.

When `py-evm` was originally written, we didn't have the additional layers between the lowest level `HexaryTrie` implementation and the base `db` object that the EVM was using, and thus, we were re-calculating the state root on **every** db write.

This was improved by wrapping the base `HexaryTrie` database in a few layers which you can find by digging into the `eth.db.account.AccountDB` object and seeing the various journals and whatnot that wrap it.  As you pointed out, the `make_state_root` function causes all of the pending changes to be written to the database and then we retrieve the resulting state root.

One way I *think* this issue could be addressed would be to add one additional layer between the base `HexaryTrie` database and the `AccountDB` such that in between transactions we can still make a `persist` call (since we need that for journaling and rolling back changes for failed transactions) but such that it doesn't actually result in writing to the underlying `HexaryTrie` database.  Then at the end of all of the block's transactions we would make an additional call to some new API which persisted all of the changes down into the `HexaryTrie` database and computed the state root.

It'll take some investigation to dig up exactly where the changes need to go as well as figuring out a clean way for this new API to be implemented.

**Comment by rayrapetyan** [comment]
[acc_dbs.pdf](https://github.com/ethereum/py-evm/files/2730226/acc_dbs.pdf)
Attached AccountDB schema.

**Comment by pipermerriam** [comment]
I was merely proposing one way this could be accomplished.  If you think you've got an idea that's cleaner :+1: .  It's typically hard for me to evaluate architecture ideas without some for of code to look at because there are a lot of subtleties that are hard to track/manage/account-for in this type of discussion.  Maybe take a minimal stab at implementing this and we can continue the discussion there?

**Comment by carver** [comment]
> "stop calculating state root" also mean stop calling persist() (which I think is wrong?)

Like Piper said, it's hard to evaluate without looking at the code, but in general: yes, we can/should stop  persisting after every transaction. We only need the state at the block boundary to be stored in the database. That might mean changing from `persist` to `commit`, but I haven't been digging in that code for a while. Feel free to take a first WIP stab at it.

**Comment by rayrapetyan** [comment]
Looks like if we just stop calling make_state_root (and all kind of persist\commit) inside apply_transaction, we reach our goal. Using existing Journals we can rollback\commit whenever we need.

**Comment by cburgdorf** [comment]
Looks like this can be closed (#1716 solved this)
