### ISSUE TITLE
DAO fork-choice issue

### ISSUE THREAD

**Issue by mateuszk87** [ethereum/py-evm#865]
* Trinity version: trinity-0.1.0a3
* OS: linux
* Python Version (python --version): Python 3.6.3 
 
### What is wrong?
When doing fullsync with trinity the DAO fork is incorrectly handled and ETC chain followed.

Trinity has been run as follows:

```
trinity --sync-mode full
```

Syncronization works:

```
 trinity attach
 w3.eth.getBlock(5000000)
Out[41]:
AttributeDict({'difficulty': 153555857798073,
 'extraData': HexBytes('0x4554432065746865726d696e65202d20555331'),
 'gasLimit': 4700036,
 'gasUsed': 51416,
 'hash': HexBytes('0xb2f55d12af971452c3669669380e03040ff01fabb64afec6bfddb3052dbd0117'),
 'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000080000000000000000020000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000008000000000000000'),
 'mixHash': HexBytes('0x36a33662da9d77511a4580dceb57f46b261247134ffd126398c2fcbff34acae9'),
 'nonce': HexBytes('0x4c85a020172afc4d'),
 'number': 5000000,
 'parentHash': HexBytes('0x001717abe8e5d60afaaa9fd2d62ab9e3a59c711fe7b66b2d9d47162c63d9e9ec'),
 'receiptsRoot': HexBytes('0xcdfeee56af33c91c592567852d74b647801f0355c5160ea42dffbebd25b56d58'),
 'sha3Uncles': HexBytes('0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347'),
 'stateRoot': HexBytes('0x94dbf3aa3242e0039dcb327806652e2c4620eff111a628a2c9488e70d0b10a30'),
 'timestamp': 1513013050,
 'transactionsRoot': HexBytes('0x3063dfd1bda002b2a8737d9ce1d1148f3d178f7a224b92b1419b3c005944c4d7'),
 'miner': '0xDf7D7e053933b5cC24372f878c90E62dADAD5d42',
 'totalDifficulty': 179580593652975622022,
 'uncles': [],
 'size': 763,
 'transactions': [HexBytes('0x9d2f76af534006c0d40e23af572925fba31994597991173f997ba0fc1764af91'),
  HexBytes('0x11c2d6c664d2527ff33e0fc184b946a0d72e86eec03a02134f0162bb8a7dc5b4')]})
```

This block corresponds to ETC http://etcchain.com/block/number/5000000 

### How can it be fixed

Fork-choice rule for DAO fork (block height 1919999 -> 1920000) needs to be re-evaluated.

**Comment by pipermerriam** [comment]
Thanks for reporting.  I suspect this has to do with how fast syncing works since I know we have proper code to handle the dao fork when doing a regular full sync (processing every block).

**Comment by pipermerriam** [comment]
Sounds like the 10 headers after the fork have special extra data that we may not be enforcing/generating/checking.

**Comment by pipermerriam** [comment]
See bottom of this blog post for extra data spec: https://blog.slock.it/hard-fork-specification-24b889e70703

**Comment by gsalgado** [comment]
When fast-syncing we just fetch block data (by block number) and store that in the DB, so I think what we're missing is a check to ensure that all peers we fetch data from are on the same chain

**Comment by gsalgado** [comment]
If that's really the case, it may also be the cause of #837

**Comment by carver** [comment]
> Sounds like the 10 headers after the fork have special extra data that we may not be enforcing/generating/checking.
> See bottom of this blog post for extra data spec: https://blog.slock.it/hard-fork-specification-24b889e70703

Specifically, the extra data in those headers must be the bytes represented by this hex encoding: `0x64616f2d686172642d666f726b` (Which is the UTF-8 encoding of the string `'dao-hard-fork'`)

**Comment by gsalgado** [comment]
So, with #883 we're going to disconnect from a anti-DAO-fork peer as long as we end up fetching one of the 10 blocks starting at 1920000, but otherwise we're going to remain connected, using a peer slot, generating unnecessary traffic and consuming CPU (for block/tx relaying that will always fail). Same if we connect to a anti-DAO-fork peer when we already have block 1920000 (which is going to be a common occurrence).

Maybe it's still desirable for us to check whether the peer is anti-DAO-fork upon connecting?  Although now we could implement it in a generic way, by fetching the block numbers from `vm_configuration` and feeding them to the new `validate_header()` class method

**Comment by gsalgado** [comment]
Also, the failures we'll get when processing blocks/txs relayed by peers on the other side of the fork could cause unexpected errors to show up in the logs, which would lead users to mistakenly think there's something buggy on our side, no?

**Comment by carver** [comment]
If we are not synced up to 1920000 yet, then all the ETC blocks/headers they send us for syncing are valid, so maybe it's fine to stay connected until we're synced to the fork.

Once we're past the fork, then won't the [long distance reorg check](https://github.com/ethereum/py-evm/blob/master/p2p/lightchain.py#L201-L203) make us drop them? Looking...

I don't see explicit handling of a long distance reorg anywhere, actually. The error message says "no common ancestors", but I don't see how it handles the case where the peer sends back headers, but the oldest header they send has a parent header that we don't have. Right now the validation would crash when trying to look up the parent header, I think. Maybe we should explicitly check if we have the parent header when we fetch.

**Comment by gsalgado** [comment]
If we're past block 1920000 and try to *fetch headers* from an ETC peer, we'll fail because we can't find a common ancestor. Currently that will just crash (IIRC), and although we can fix it so that we don't crash, at that time we'd have to stop and request block 1920000 from the peer in order to figure out if it's just a peer on the wrong side of the DAO fork or something wrong on our side (e.g. a reorg deeper than we support).

Also, when we start relaying transactions, how would that work for transactions sent to us by ETC peers?  IIUC, they won't apply on our blocks and we'd, again, have to do the is-this-peer-anti-DAO check.

And I bet I'm overlooking other situations in which we would have issues caused by being connected to ETC peers, and in each of those we'd have to check if that's indeed because of an ETC peer or a legit error, so we could end up having to do this is-this-peer-anti-DAO check in lots of different places.

Since it only makes any sense for us to be connected to an ETC peer up until we've synced block 1920000, it'd be simpler for us to do the check upon connecting, and disconnect if it's an ETC peer, but more importantly I believe that'd save us trouble down the line by ensuring we don't have to worry about checking if an error is because we're trying to sync from an ETC peer

**Comment by pipermerriam** [comment]
I think I'm mirroring what @gsalgado just said, but I think we should just avoid connecting to ETC peers entirely when dao support is true.  Even though they *can* give us valid headers it will add complication to the sync code to negotiate dropping all of the ETC peers at the point we pass the dao fork block.  I'd rather just abort early and ensure we're only connected to pro-fork peers.

**Comment by carver** [comment]
:+1: Now the question is: how do we do that without adding any VM-specific logic into the p2p. First instinct:

When connecting to a new peer, we iterate through all the VMs in `Chain.vm_configuration`:
- For VM 0, check the genesis header against our own genesis header
- For VM 1-N:
  - Check if the peer is synced to the starting block of the VM. If not, connect successfully
  - Request the header at the starting block of the VM and it's parent header
  - Run `VM.validate_header(header, parent_header)`, and disconnect if validation fails
- If the last VM validates, connect successfully

**Comment by gsalgado** [comment]
I'm thinking that it may not make sense to do the fetch-header-and-validate dance for every item in `Chain.vm_configuration` as most of the forks they represent didn't actually cause a chain split (like the DAO fork did). Since for each of them we'd do an extra request-header/wait-for-reply roundtrip, I'd rather avoid that, but in order to do so in a generic way we'd need to somehow distinguish the items in `Chain.vm_configuration` for which we must do the validation dance. How do you guys feel about adding an extra attribute to `BaseVM` for that, something like `caused_chain_split`?

**Comment by gsalgado** [comment]
#869 has been updated to do what I described above. How do you guys feel about it?
