### ISSUE TITLE
Update aiohttp to > 3.*

### ISSUE THREAD

**Issue by mindergrinder** [ethereum/py-evm#958]
* py-evm Version: 0.2.0a26
* OS: linux
* Python Version 3.6

### What is wrong?

Aiohttp dependency is quite ubiquitous and using old version prevents including py-evm in many projects.

### How can it be fixed

It should be minor update according to: https://docs.aiohttp.org/en/stable/changes.html

**Comment by cburgdorf** [comment]
I may be wrong but I'm not sure if that library is actually in use anywhere right now. Trinity does currently not provide an http server built-in and there are currently no plans to provide that functionality built-in because there are other adapter-like mechanisms that people may use in the future to get an HTTP interface to Trinity.

I did a quick search on `aiohttp` across the source code and the only place where I see it is in the dependency list.

**Comment by carver** [comment]
I'm inferring from this commit that it's eth-tester that requires aiohttp < 3 https://github.com/ethereum/py-evm/commit/df84ff208f2e7656bb9206afa3a94cc1bc83393c

Maybe it was simply a bug that that requirement slipped in, though. Before we simply delete the line, do you remember why it was added @hwwhww ?

**Comment by hwwhww** [comment]
@carver I'm so sorry I just saw I was tagged, and don't have the memory of why I added it. I guess it was for `async_lru` for some reason. And now the `async_lru` dependency is only for `p2p`, not for `evm`. Again, apologies for that I should have another commit to fix it and poor memory.

I think we can just remove it all `aiohttp` and the `async_lru` of `evm`. I will fix it.

**Comment by cburgdorf** [comment]
This can now be closed as we got rid of the dependencies.
