### ISSUE TITLE
Add testing for Python 3.7

### ISSUE THREAD

**Issue by carver** [ethereum/py-evm#970]
### What is wrong?

Python 3.7 stable has been released: https://pythoninsider.blogspot.com/2018/06/python-3.html
We are not currently running any tests against it.

### How can it be fixed

Start running the core tests against py3.7 in addition to the current python envs.

**Comment by veox** [comment]
CircleCI does not yet provide machine images with pre-installed Python 3.7 stable release - only beta 5 and the release candidate.

Watch [docs](https://circleci.com/docs/2.0/circleci-images/#python) or [docker hub](https://hub.docker.com/r/circleci/python/tags/) (linked from docs) for when those become available.

**Comment by veox** [comment]
Some dependencies might not yet support Python 3.7: see [failed job](https://circleci.com/gh/veox/py-evm/99):

```
idna-ssl requires Python '<3.7.0' but the running Python is 3.7.0
```

For ref, I used [this branch of mine](https://github.com/veox/py-evm/tree/test-core-with-py3.7rc). It requests the `python3.7-rc` image from CircleCI, but manual inspection via SSH shows the machine had beta 5 installed:

```
circleci@e5fdac382095:~$ python --version
Python 3.7.0b5
```

**Comment by carver** [comment]
The first exploratory steps of seeing what else is broken besides `idna-ssl` can be started. Totally agree that we should wait until a stable 3.7 image is released before it goes into CI.

**Comment by veox** [comment]
Images with Python 3.7.0 (the stable version) have become available.

I've made [a new branch](https://github.com/veox/py-evm/commits/test-core-with-py3.7) and directed it to use this new machine image, but [there are still dependency problems](https://circleci.com/gh/veox/py-evm/134).

Summary:

The `plyvel` Python package [does not have a pre-built `wheel` available for Python 3.7](https://pypi.org/project/plyvel/#files); so the `tox` run attempts to build the package itself; the system packages `libleveldb-dev` and `libgmp-dev` are not installed on the (Debian 9, "Stretch") machine, so the build fails.

After SSH'ing in and installing them, the build still fails, with same error as in https://github.com/wbolster/plyvel/issues/62, i.e. because building `plyvel` requires `leveldb` header version at least 1.20, whereas Stretch has 1.18.

Possible approaches:

1. wait for `plyvel` to get a py3.7 wheel, or help it happen; alternatively,
2. enable the Debian `testing` repo ("Buster"), which [has `libleveldb-dev` 1.20](https://packages.debian.org/search?searchon=names&keywords=libleveldb-dev).

(2) can get very brittle, so IMO best avoid it.

**Comment by pipermerriam** [comment]
We can probably open a PR to `plyvel` to enable testing against 3.7.  Once that is passing I doubt it would take too much coaxing to get them to push out a new release with 3.7 support.

Alternatively, we've wanted to explore RocksDB (but I don't know if whatever python library sits on top of that supports 3.7 either)

**Comment by dylanjw** [comment]
It looks like plyvel 1.05 has been pushed with a py3.7 wheel
